apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlphttp:
        endpoint: http://mimir-nginx.mimir-test.svc:80/otlp
        tls:
          insecure: true
      otlphttp/logs:
        endpoint: http://loki-distributor.loki.svc.cluster.local:3100/otlp
        tls:
          insecure: true
      otlp:
        endpoint: http://tempo-distributor.tempo.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          exporters: [otlphttp/logs]
