apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      prometheusremotewrite:
        endpoint: http://prometheus-server.prometheus.svc.cluster.local/api/v1/write
        tls:
          insecure: true
      otlphttp/loki:
        endpoint: http://loki-distributed-distributor.loki.svc.cluster.local:3100/loki/api/v1/push
        tls:
          insecure: true
      otlp:
        endpoint: http://tempo-distributor.tempo.svc.cluster.local:9095
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          exporters: [otlphttp/loki]

