apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: otel-builder
spec:
  tag: nazia141/otel:1.0
  serviceAccountRef:
    name: default-service-account
    namespace: kpack
  stack:
    name: default-base
    kind: ClusterStack
  store:
    name: default-clusterstore
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
    - id: paketo-buildpacks/opentelemetry
  - group:
    - id: paketo-buildpacks/nodejs

